# See config options at https://alacritty.org/config-alacritty.html

[window]
padding = { x = 5, y = 0 }
opacity = 0.95
blur = true
decorations = "Full" # or "None"
dynamic_title = true
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 14.0

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 550
blink_timeout = 0

[terminal]
shell = { program = "/bin/zsh", args = ["-lc", "tmux attach || tmux"] }

# [[keyboard.bindings]]
# key = "V"
# mods = "Control|Shift"
# action = "Paste"

# [[keyboard.bindings]]
# key = "C"
# mods = "Control|Shift"
# action = "Copy"

# [mouse]
# hide_when_typing = true