"$schema" = 'https://starship.rs/config-schema.json'


# # Uncomment to move prompt to right side and input right below on left
# # example:
# #                         ~/path/to/directory
# # > echo "Hello, World"
# #
# add_newline = false
# format = """$fill$all$character"""

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[directory]
style = "bg:surface0 fg:text"
format = "[î‚¶](surface0)[$path]($style)[î‚°](surface0) "
read_only = " ó°Œ¾"

[git_branch]
style = "maroon"
symbol = "ï˜ "

[git_commit]
tag_symbol = ' ï’ '

[git_status]
style = "#ca2828"

[docker_context]
symbol = "ïŒˆ "

[aws]
symbol = "îŒ½ "

[gcloud]
symbol = "îŸ± "

[package]
disabled = true
symbol = "ó°— "

[fossil_branch]
symbol = "ï˜ "

[bun]
format = "via [$symbol]($style)"
symbol = "î¯ "

[buf]
format = "with [$symbol]($style)"
symbol = "ï’ "

[c]
format = "via [$symbol($name)]($style)"
symbol = "î˜ "

[cmake]
format = "via [$symbol]($style)"
symbol = "î” "

[cobol]
format = "via [$symbol]($style)"

[conda]
symbol = "ï„Œ "

[cpp]
format = "via [$symbol($name)]($style)"
symbol = "î˜ "

[crystal]
format = "via [$symbol]($style)"
symbol = "î˜¯ "

[daml]
format = "via [$symbol]($style)"

[dart]
format = "via [$symbol]($style)"
symbol = "î˜ "

[deno]
format = "via [$symbol]($style)"
symbol = "îŸ€ "

[dotnet]
format = "[$symbol(ğŸ¯ $tfm )]($style)"

[elixir]
format = '[$symbol]($style)elixir'
symbol = "î˜­ "

[elm]
format = '[$symbol]($style)elm'
symbol = "î˜¬ "

[erlang]
format = '[$symbol]($style)erlang'

[fennel]
format = '[$symbol]($style)fennel'
symbol = "îš¯ "

[fortran]
format = '[$symbol]($style)fortran'
symbol = "îŸ "

[gleam]
format = '[$symbol]($style)gleam'

[golang]
format = '[$symbol]($style)golang'
symbol = "î˜§ "

[gradle]
format = '[$symbol]($style)gradle'
symbol = "î™  "

[guix_shell]
symbol = "ïŒ¥ "

[haskell]
format = '[$symbol]($style)haskell'
symbol = "î· "

[haxe]
format = '[$symbol]($style)haxe'
symbol = "î™¦ "

[hg_branch]
symbol = "ï˜ "

[hostname]
ssh_symbol = "î¬ "

[helm]
format = '[$symbol]($style)helm'
symbol = "îŸ» "

[java]
format = '[$symbol]($style)java'
symbol = "î‰– "

[julia]
format = '[$symbol]($style)julia'
symbol = "î˜¤ "

[kotlin]
format = '[$symbol]($style)kotlin'
symbol = "î˜´ "

[lua]
format = '[$symbol]($style)lua'
symbol = "î˜  "

[memory_usage]
symbol = "ó°› "

[meson]
format = '[$symbol]($style)meson'
symbol = "ó°”· "

[mojo]
format = 'with [$symbol]($style)'

[nim]
format = '[$symbol]($style)nim'
symbol = "ó°†¥ "

[nix_shell]
symbol = "ïŒ“ "

[nodejs]
format = '[$symbol]($style)nodejs'
symbol = "îœ˜ "

[ocaml]
format = '[$symbol(\($switch_indicator$switch_name\) )]($style)ocaml'
symbol = "î™º "

[odin]
format = '[$symbol]($style)odin'

[opa]
format = '[$symbol]($style)opa'

[perl]
format = '[$symbol]($style)perl'
symbol = "î™¾ "

[php]
format = '[$symbol]($style)php'
symbol = "î˜ˆ "

[pijul_channel]
symbol = "ï˜ "

[pixi]
format = '[$symbol($environment )]($style)pixi'
symbol = "ó°— "

[pulumi]
format = '[$symbol$stack]($style)pulumi'

[purescript]
format = '[$symbol]($style)purescript'

[python]
# format = '[$symbol]($style)python'
format = '[${symbol}${pyenv_prefix}(\($virtualenv\) )]($style)python'
symbol = 'î˜† '
style = '#306998'

[quarto]
format = '[$symbol]($style)quarto'

[raku]
format = '[$symbol]($style)raku'

[red]
format = '[$symbol]($style)red'

[rlang]
format = '[$symbol]($style)rlang'
symbol = "ó°Ÿ” "

[ruby]
format = '[$symbol]($style)ruby'
symbol = "î‘ "

[rust]
format = '[$symbol]($style)rust'
symbol = "ó±˜— "

[scala]
format = '[$symbol]($style)scala'
symbol = "îœ· "
style = '#ff0000'

[solidity]
format = '[$symbol]($style)solidity'

[swift]
format = '[$symbol]($style)swift'
symbol = "î• "

[typst]
format = '[$symbol]($style)typst'

[vagrant]
format = '[$symbol]($style)vagrant'

[vlang]
format = '[$symbol]($style)vlang'

[xmake]
format = "via [$symbol]($style)"
symbol = "î” "

[zig]
format = '[$symbol]($style)zig'
symbol = "îš© "

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
AOSC = "ïŒ "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CachyOS = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Elementary = "ïŒ‰ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Ios = "ó°€· "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
Nobara = "ï€ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "
Zorin = "ïŒ¯ "

[status]
symbol = "ï‘§ "