"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[bun]
format = "via [$symbol]($style)"

[buf]
format = "with [$symbol]($style)"

[c]
format = "via [$symbol($name)]($style)"

[cmake]
format = "via [$symbol]($style)"

[cobol]
format = "via [$symbol]($style)"

[cpp]
format = "via [$symbol($name)]($style)"

[crystal]
format = "via [$symbol]($style)"

[daml]
format = "via [$symbol]($style)"

[dart]
format = "via [$symbol]($style)"

[deno]
format = "via [$symbol]($style)"

[dotnet]
format = "[$symbol(ðŸŽ¯ $tfm )]($style)"

[elixir]
format = '[$symbol]($style)elixir'

[elm]
format = '[$symbol]($style)elm'

[erlang]
format = '[$symbol]($style)erlang'

[fennel]
format = '[$symbol]($style)fennel'

[fortran]
format = '[$symbol]($style)fortran'

[gleam]
format = '[$symbol]($style)gleam'

[golang]
format = '[$symbol]($style)golang'

[gradle]
format = '[$symbol]($style)gradle'

[haskell]
format = '[$symbol]($style)haskell'

[haxe]
format = '[$symbol]($style)haxe'

[helm]
format = '[$symbol]($style)helm'

[java]
format = '[$symbol]($style)java'

[julia]
format = '[$symbol]($style)julia'

[kotlin]
format = '[$symbol]($style)kotlin'

[lua]
format = '[$symbol]($style)lua'

[meson]
format = '[$symbol]($style)meson'

[mojo]
format = 'with [$symbol]($style)'

[nim]
format = '[$symbol]($style)nim'

[nodejs]
format = '[$symbol]($style)nodejs'
symbol = 'ó°Ž™ '

[ocaml]
format = '[$symbol(\($switch_indicator$switch_name\) )]($style)ocaml'

[odin]
format = '[$symbol]($style)odin'

[opa]
format = '[$symbol]($style)opa'

[perl]
format = '[$symbol]($style)perl'

[php]
format = '[$symbol]($style)php'

[pixi]
format = '[$symbol($environment )]($style)pixi'

[pulumi]
format = '[$symbol$stack]($style)pulumi'

[purescript]
format = '[$symbol]($style)purescript'

[python]
format = '[$symbol]($style)python'
symbol = 'î˜† '
style = '#306998'

[quarto]
format = '[$symbol]($style)quarto'

[raku]
format = '[$symbol]($style)raku'

[red]
format = '[$symbol]($style)red'

[rlang]
format = '[$symbol]($style)rlang'

[ruby]
format = '[$symbol]($style)ruby'

[rust]
format = '[$symbol]($style)rust'

[scala]
format = '[$symbol]($style)scala'
symbol = 'îœ· '
style = '#ff0000'

[solidity]
format = '[$symbol]($style)solidity'

[swift]
format = '[$symbol]($style)swift'

[typst]
format = '[$symbol]($style)typst'

[vagrant]
format = '[$symbol]($style)vagrant'

[vlang]
format = '[$symbol]($style)vlang'

[xmake]
format = "via [$symbol]($style)"

[zig]
format = '[$symbol]($style)zig'
